#!/bin/sh
#
# Check that every file that carries the release version agrees with
# NXT_VERSION in the version file.
#
# The version file is the source of truth.  configure, auto/make and the
# pkg/{deb,rpm,docker,npm} Makefiles read it directly.  The files listed in
# .github/scripts/version-sites cannot read it, so a release commit edits
# them by hand or with tools/bump-version.sh.  At 1.37.0 three Dockerfiles
# kept 1.36.1 in the tag; this script finds that kind of mistake before a
# merge.
#
# NXT_VERSION must be X.Y.Z.  Then each row of version-sites is checked by
# its kind, as that file describes.  For "dockerfiles", "make dockerfiles"
# runs in a temporary copy, and a Dockerfile in the tree that differs, is
# missing, or is no longer generated is an error.  The rows also hold
# pins: versions that are not the release version, but must agree across
# files.
#
# Run it from anywhere in the tree.  It needs sh, sed, awk, grep, make and
# jq.  It changes no file and uses no network.

set -eu

root=$(cd "$(dirname "$0")/../.." && pwd)
cd "$root"

sites=.github/scripts/version-sites
tab=$(printf '\t')
fail=0
tmp=

# A trap that does not exit lets the script go on after the signal, so
# INT and TERM exit, and the EXIT trap removes the temporary directory.
trap '[ -z "$tmp" ] || rm -rf "$tmp"' EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

err() {
    printf 'check-version: %s\n' "$*" >&2
    fail=1
}

# The distinct lines of standard input, on one line.
distinct() {
    sort -u | paste -sd ' ' -
}

# One line, or the check below fails on a duplicate.
ver=$(sed -n 's/^NXT_VERSION=//p' version | distinct)

if ! printf '%s\n' "$ver" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    err "version: NXT_VERSION is \"$ver\", not X.Y.Z"
    exit 1
fi

num=$(printf '%s\n' "$ver" | awk -F. '{ print $1 * 10000 + $2 * 100 + $3 }')

# A version as a basic regular expression: the dots match only dots.
bre() {
    printf '%s' "$1" | sed 's/\./\\./g'
}

re=$(bre "$ver")
minor_re=${re%\\.*}

# site FILE VALUE WANT: FILE carries VALUE, which must be WANT.
site() {
    if [ "$2" != "$3" ]; then
        err "$1: carries \"$2\", the version file has $3"
    fi
}

# The [package] version of a Cargo.toml.
crate() {
    awk '/^\[/ { p = ($0 == "[package]") }
         p && /^version *=/ { gsub(/^version *= *"|".*$/, ""); print; exit }' "$1"
}

# The version of one package in a Cargo.lock.
locked() {
    awk -v n="name = \"$2\"" '$0 == n { f = 1; next }
         f && /^version = / { gsub(/^version = "|"$/, ""); print; exit }' "$1"
}

# The X.Y.Z values that follow the extended regular expression $2 in $1.
pins() {
    grep -oE -e "$2[0-9]+\.[0-9]+\.[0-9]+" "$1" \
        | grep -oE '[0-9]+\.[0-9]+\.[0-9]+$' || true
}

# Run "make dockerfiles" for directory $1 in a copy and compare.
dockerfiles() {
    d=$1
    tmp=$(mktemp -d)

    mkdir -p "$tmp/$d"
    cp version "$tmp/"
    cp pkg/eol.json pkg/shasum.mak "$tmp/pkg/"
    cp "$d/Makefile" "$d/template.Dockerfile" "$tmp/$d/"

    # The Makefile sets VERSION, MODULES, VARIANT and VERSIONS_<module>
    # with "?=", so an exported variable of the same name would change the
    # output.  Run make with no environment but PATH.
    if ! env -i PATH="$PATH" make -s -C "$tmp/$d" dockerfiles \
         < /dev/null > "$tmp/make.log" 2>&1
    then
        cat "$tmp/make.log" >&2
        err "$d: \"make dockerfiles\" failed"
    fi

    for f in "$tmp/$d"/Dockerfile.*; do
        [ -e "$f" ] || continue
        name=${f##*/}
        if [ ! -f "$d/$name" ]; then
            err "$d/$name: generated by \"make dockerfiles\", not in the tree"
        elif ! cmp -s "$f" "$d/$name"; then
            err "$d/$name: differs from \"make dockerfiles\" output"
            diff -u "$d/$name" "$f" | sed -n '3,40p' >&2 || true
        fi
    done

    for f in "$d"/Dockerfile.*; do
        name=${f##*/}
        case $name in
        Dockerfile.builder-*)
            # Written by hand; not generated from the template.
            continue ;;
        esac
        [ -f "$tmp/$d/$name" ] \
            || err "$f: not generated by \"make dockerfiles\"; is it still in pkg/eol.json?"
    done

    rm -rf "$tmp"
    tmp=
}

while IFS=$tab read -r path kind a1 a2; do
    case $path in
    ''|'#'*)
        continue ;;
    esac

    if [ ! -e "$path" ]; then
        err "$path: listed in $sites, but does not exist"
        continue
    fi

    case $kind in
    # Every line that matches: bump-version.sh rewrites each one, so a
    # stale duplicate must not pass.
    line)
        got=$(sed -n "s#^$a1\(.*\)$a2\$#\1#p" "$path" | distinct)
        if [ -z "$got" ]; then
            err "$path: no line matches ^${a1}X.Y.Z${a2}\$"
        else
            site "$path" "$got" "$ver"
        fi ;;
    vernum)
        got=$(sed -n "s#^$a1##p" "$path" | distinct)
        if [ -z "$got" ]; then
            err "$path: no line matches ^${a1}NNNNN\$"
        else
            site "$path (NXT_VERNUM)" "$got" "$num"
        fi ;;
    cargo-package)
        got=$(crate "$path")
        if [ -z "$got" ]; then
            err "$path: no version in the [package] table"
        else
            site "$path" "$got" "$ver"
        fi ;;
    cargo-lock)
        got=$(locked "$path" "$a1")
        if [ -z "$got" ]; then
            err "$path: no version for the package $a1"
        else
            site "$path ($a1)" "$got" "$ver"
        fi ;;
    dockerfiles)
        dockerfiles "$path" ;;
    changelog-md)
        grep -q "^## \[$re\]" "$path" \
            || err "$path: no \"## [$ver]\" section"
        grep -q "^\[$re\]: " "$path" \
            || err "$path: no \"[$ver]:\" link"
        # [Unreleased] compares from the released version, not an older one.
        grep -q "^\[Unreleased\]: .*/compare/unitctl/$re\.\.\.HEAD\$" "$path" \
            || err "$path: [Unreleased] does not compare from unitctl/$ver" ;;
    security-md)
        # Match the status cell exactly: "✅ Active" or "✅ LTS".  LC_ALL=C
        # makes grep match the check mark byte by byte in any locale.
        LC_ALL=C grep -Eq "^\\| *$minor_re\\.x *\\| *✅ *(Active|LTS) *\\|" "$path" \
            || err "$path: no ${ver%.*}.x row whose status cell is \"✅ Active\" or \"✅ LTS\""
        # Exactly one line is Active.  A release that makes a new line Active
        # must retire the one before it.
        n=$(LC_ALL=C grep -Ec '^\| *[^|]*\| *✅ *Active *\|' "$path" || true)
        if [ "$n" -ne 1 ]; then
            err "$path: $n rows say Active, expected one"
        fi ;;
    changes)
        grep -q "^Changes with FreeUnit $re " "$path" \
            || err "$path: no \"Changes with FreeUnit $ver\" block"
        top=$(sed -n 's/^Changes with FreeUnit \([0-9.]*\) .*/\1/p' "$path" \
              | head -n 1)
        for v in "$ver" "$top"; do
            n=$(grep -c "ver=\"$(bre "$v")\"" "$a1" || true)
            if [ "$n" != 2 ]; then
                err "$a1: $n stanzas with ver=\"$v\", expected 2"
            fi
        done ;;
    pin-source|pin)
        case $a1 in
        ''|*[!a-z0-9_]*)
            err "$sites: bad pin name \"$a1\" for $path"
            continue ;;
        esac
        got=$(pins "$path" "$a2" | sort -u)
        if [ "$kind" = pin-source ]; then
            if [ "$(printf '%s\n' "$got" | grep -c .)" != 1 ]; then
                err "$path: pin $a1 source gives \"$got\", expected one X.Y.Z"
                continue
            fi
            eval "pin_$a1=\$got"
            continue
        fi
        eval "want=\${pin_$a1:-}"
        if [ -z "$want" ]; then
            err "$sites: pin $a1 is used by $path before its pin-source row"
        elif [ -z "$got" ]; then
            err "$path: no pin $a1 after \"$a2\""
        else
            for v in $got; do
                [ "$v" = "$want" ] \
                    || err "$path: pin $a1 is $v after \"$a2\", the source has $want"
            done
        fi ;;
    *)
        err "$sites: unknown kind \"$kind\" for $path" ;;
    esac
done < "$sites"

if [ "$fail" -ne 0 ]; then
    printf 'check-version: FAILED for %s\n' "$ver" >&2
    exit 1
fi

printf 'check-version: every version site carries %s\n' "$ver"
